"""
orchestrator/agents/sql_agent.py
"""
import json
import os
import re
from typing import Dict, List
from llama_cpp import Llama


class SqlAgent:
    def __init__(self, model_path: str = "./models/Phi-3-mini-4k-instruct-q4.gguf"):
        """CPU-optimized GGUF inference via llama.cpp bindings."""
        n_threads = os.cpu_count() or 4
        print(f"⚙️ Loading GGUF model from {model_path} using {n_threads} threads...", flush=True)

        self.llm = Llama(
            model_path=model_path,
            n_ctx=4096,            # match your GGUF build's context window
            n_threads=n_threads,
            n_gpu_layers=0,        # set >0 if you build with Metal/CUDA support to offload layers
            verbose=False,
            chat_format="phi-3", 
        )
        print("✅ Model loaded.", flush=True)

    def build_db_context_queries(self, canonical_json: Dict) -> List[str]:
        queries = []
        pricer_descr = canonical_json.get("pricer_type_description")
        if pricer_descr:
            safe_pricer = str(pricer_descr).replace("'", "''")
            queries.append(f"SELECT * FROM LUT_PricerType WHERE pricertypedescr = '{safe_pricer}';")
        else:
            queries.append("SELECT * FROM LUT_PricerType WHERE pricertypedescr LIKE '%Pro%';")
        return queries

    def _build_safe_sql_fallback(self, fallback_text: str = "") -> str:
        if fallback_text and fallback_text.strip():
            sql_lines = []
            for line in fallback_text.splitlines():
                stripped = line.strip()
                if not stripped:
                    continue
                if stripped.startswith(("--", "/*", "*/")):
                    continue
                if re.search(r"\b(SELECT|INSERT|UPDATE|DELETE|CREATE|ALTER|DROP|MERGE|BEGIN|END|DECLARE|WITH|FROM|WHERE|VALUES|SET|JOIN|LEFT|RIGHT|INNER|OUTER|CASE|THEN|ELSE|GO|USE|IF|EXEC|RETURN|AND|OR|AS)\b", stripped.upper()):
                    sql_lines.append(stripped)
            if sql_lines:
                return "\n".join(sql_lines[:20]).strip()

        return "BEGIN TRANSACTION;\n-- No valid SQL generated by the model. Add the required statements here.\nCOMMIT TRANSACTION;"

    def _sanitize_generated_sql(self, raw_text: str, fallback_text: str = "") -> str:
        if not raw_text:
            return self._build_safe_sql_fallback(fallback_text)

        cleaned = raw_text.replace("\x00", "")
        cleaned = cleaned.replace("```sql", "").replace("```", "")
        cleaned = re.sub(r"<think[^>]*>.*?</think>", "", cleaned, flags=re.S | re.I)

        sql_keywords = [
            "SELECT", "INSERT", "UPDATE", "DELETE", "CREATE", "ALTER", "DROP", "MERGE",
            "BEGIN", "END", "DECLARE", "WITH", "FROM", "WHERE", "VALUES", "SET", "JOIN",
            "LEFT", "RIGHT", "INNER", "OUTER", "CASE", "THEN", "ELSE", "GO", "USE", "IF",
            "EXEC", "RETURN", "AND", "OR", "AS"
        ]
        upper_text = cleaned.upper()
        has_sql_keywords = any(keyword in upper_text for keyword in sql_keywords)

        sql_lines = []
        for line in cleaned.splitlines():
            stripped = line.strip()
            if not stripped:
                continue
            if stripped.startswith(("--", "/*", "*/")):
                continue
            if re.search(r"\b(SELECT|INSERT|UPDATE|DELETE|CREATE|ALTER|DROP|MERGE|BEGIN|END|DECLARE|WITH|FROM|WHERE|VALUES|SET|JOIN|LEFT|RIGHT|INNER|OUTER|CASE|THEN|ELSE|GO|USE|IF|EXEC|RETURN|AND|OR|AS)\b", stripped.upper()):
                sql_lines.append(stripped)
            elif re.search(r"^\s*\[dbo\]|^\s*\w+\s*\(|^\s*\w+\s*\[", stripped):
                sql_lines.append(stripped)

        if sql_lines:
            candidate = "\n".join(sql_lines).strip()
            if len(candidate) >= 40:
                return candidate

        # If the response does not contain recognizable SQL structure, fall back to the known-safe template.
        if fallback_text and fallback_text.strip():
            if not has_sql_keywords:
                return self._build_safe_sql_fallback(fallback_text)
            if len(cleaned) < 40 and not re.search(r"\b(SELECT|INSERT|UPDATE|DELETE|CREATE|ALTER|DROP|MERGE|BEGIN|END|DECLARE|WITH|FROM|WHERE|VALUES|SET|JOIN|LEFT|RIGHT|INNER|OUTER|CASE|THEN|ELSE|GO|USE|IF|EXEC|RETURN|AND|OR|AS)\b", cleaned.upper()):
                return self._build_safe_sql_fallback(fallback_text)
            if cleaned.lstrip().startswith(("/", "*", "-", "#")):
                return self._build_safe_sql_fallback(fallback_text)

        return cleaned.strip() or self._build_safe_sql_fallback(fallback_text)

    def generate_sql(self, retrieved_context: Dict, db_context_results: Dict, script_guide_text: str, base_template_text: str, use_cot: bool = False) -> str:
        system_prompt = """You are a SQL Server regulatory SQL generation agent.
Strict rules:
1. Canonical JSON is the primary source of truth.
2. Logic guides define how to validate ADD vs UPDATE and how to plan steps.
3. Script guides and templates define SQL style and ordering.
4. DB context results resolve IDs and determine whether records already exist.
5. Generate only SQL Server SQL.
6. Return only executable SQL script statements inside Section 2.
7. If an existing state is updated and procedure order must be replaced, delete old StateProcedure rows before inserting new ordered rows.
8. If required context is missing, generate the safest valid SQL possible based on available context."""

        if use_cot:
            system_prompt += "\nStrict Requirement: Before writing any executable SQL code block, you MUST construct an isolated reasoning trace wrapped entirely inside an initial <thinking> and </thinking> XML block."
        else:
            system_prompt += "\nOutput ONLY executable SQL script statements directly. Do not include introductory notes, explanations, or thinking blocks."

        def _cap_tokens(text: str, max_tokens: int) -> str:
            token_ids = self.llm.tokenize(text.encode("utf-8"))
            if len(token_ids) <= max_tokens:
                return text
            # decode with errors="ignore" to avoid corrupting a split multi-byte token
            return self.llm.detokenize(token_ids[:max_tokens]).decode("utf-8", errors="ignore")

        prompt_context = _cap_tokens(retrieved_context["prompt_context"], 2500)
        script_guide_text = _cap_tokens(script_guide_text, 600)
        base_template_text = _cap_tokens(base_template_text, 800)
        db_context_str = _cap_tokens(json.dumps(db_context_results, indent=2), 500)

        user_prompt = f"""PROMPT CONTEXT:
{prompt_context}

DB CONTEXT RESULTS:
{db_context_str}

SCRIPT GUIDE FORMATTING RULES:
{script_guide_text}

TARGET SEGMENT COMMENT TO GENERATE UNDER:
{base_template_text}

TASK:
Generate only the SQL script modifications belonging to Section 2. Apply formatting hierarchy ordering (State -> Procedure -> ProcedureVariable -> StateProcedure). Return ONLY the clean, executable statements."""

        # Build the Phi-3 instruct prompt manually — avoids depending on
        # llama-cpp-python's chat_format registry entirely.
        full_prompt = (
            f"<|system|>\n{system_prompt}<|end|>\n"
            f"<|user|>\n{user_prompt}<|end|>\n"
            f"<|assistant|>\n"
        )

        print("🧮 Starting generation...", flush=True)
        result = self.llm.create_completion(
            prompt=full_prompt,
            max_tokens=512,
            temperature=0.0,
            stop=["<|end|>", "<|user|>"],
        )
        print("✅ Generation complete.", flush=True)

        raw_output = result["choices"][0]["text"].strip()
        return self._sanitize_generated_sql(raw_output, fallback_text=base_template_text)
    

