INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (1, N'0001', N'Return Code 25: Non-Payment Claim', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (2, N'0002', N'Return Code 21: Invalid Present On Admission (POA) Coding', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (3, N'0003', N'Return Code 27: Never Event', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (4, N'0004', N'Return Code 08: Transfer Claim Zero-Divide Error', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (5, N'0051', N'Potentially Preventable Readmission (PPR) Factor - Adjustment to Base and Outlier Add-On Payment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (6, N'0052', N'Organ Acquisition and Malpractice Pass Thru Add-On Payment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (7, N'0053', N'Base Payment - Massachusetts Medicaid', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (8, N'0200', N'Check Claim for Transfer Discharge Status Code', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (9, N'0201', N'Transfer Per Diem Payment Capped at Base + Outlier Add-On Payment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (10, N'0300', N'Costs for High Cost Outlier Add-On Payment: RCC * Charges', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (11, N'0301', N'High Cost Outlier Threshold: Base + Hospital Threshold', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (12, N'0302', N'High Cost Outlier Add-On Payment: (Costs - Threshold) * Marginal Cost Factor', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (13, N'0054', N'Policy Adjustment 1', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (14, N'0055', N'Base Payment with Policy Adjustment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (15, N'0056', N'Medical Education Add-On Payment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (16, N'0202', N'Transfer Per Diem Payment Capped at Base', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (17, N'0203', N'Interim Claim Payment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (18, N'0303', N'High Cost and Day Outlier Add-On Payment - Mississippi Medicaid', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (19, N'0001', N'Claim Level Return Code 84: Error Reading Fee Schedule File', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (20, N'0002', N'Claim Level Return Code 86: Error Reading Code Table File', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (21, N'0050', N'Line Level Return Code 16: Never Event', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (22, N'0051', N'Line Level Return Code 10: Line Item Rejection From Editor', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (23, N'0100', N'Fee Schedule Lookup', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (24, N'0101', N'Fee Schedule Payments With Charge Cap   ', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (25, N'0102', N'Packaging ', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (26, N'0103', N'Consolidation', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (27, N'0104', N'MSPD Ranking', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (28, N'0106', N'Multiple Significant Procedure Discounting', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (29, N'0107', N'Repeat Ancillary Discounting Ranking ', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (30, N'0108', N'Repeat Ancillary Discounting  ', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (31, N'0109', N'Terminated Procedure Discounting   ', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (32, N'0110', N'Bilateral Procedure Discounting   ', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (33, N'0111', N'Calculate Adjusted APG Weight And Set Basic Methods   ', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (34, N'0112', N'Base APG Payment', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (35, N'0114', N'Flat Rate Payments based on APG', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (36, N'0115', N'UB Modifier Lookup - Ohio Medicaid', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (37, N'0116', N'Procedure Code Table Lookup', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (38, N'0117', N'Pharmaceuticals and Devices with UB Modifier  - Ohio Medicaid', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (39, N'0118', N'Vaccine For Children', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (40, N'NEED', N'Always be included', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (41, N'NEED', N'Always be included', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (42, N'0119', N'Policy Adjustments', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (43, N'0005', N'Birth Weight Age Limit', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (44, N'0006', N'Return Code 46: Invalid Birth Weight in Grams', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (45, N'0057', N'Policy Adjustment 2', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (46, N'0204', N'Exclude certain DRGs from Transfer Per Diem', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (47, N'0304', N'High Cost Outlier with Two Marginal Cost Factors', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (48, N'0500', N'Charge Cap', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (49, N'0501', N'Policy Add-on 1', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (50, N'0502', N'Markup', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (51, N'0003', N'Claim Level Return Code 22: Denial Claim', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (52, N'0052', N'Line Level Return Code 29: Non-covered services', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (53, N'0113', N'Markup', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (54, N'0120', N'Calculate Cost - Day Level', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (55, N'0121', N'Calculate Threshold - Day Level', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (56, N'0122', N'High Cost Outlier - Day Level', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (57, N'0123', N'Multi Channel Pricing', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (58, N'0105', N'Prepare Cross Type Ranking for APG Types 2 and 25', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (59, N'0305', N'Low Cost Outlier Gross Gain Calculation', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (60, N'0306', N'Low Cost Outlier Calculation', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (61, N'0053', N'Line Level Return Code 07: Manually Priced/Paid by Report', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (62, N'0124', N'Standard Payment with Charge Cap (discounting)', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (63, N'0125', N'Percent of Costs with Discount', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (64, N'0126', N'Fee Schedule Pricing with Charge Cap with discount', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (65, N'0127', N'Fee Schedule Pricing without Charge Cap', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (66, N'0128', N'Observation - Ohio Medicaid', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (67, N'0129', N' Pharmaceuticals, no UB modifier - Ohio Medicaid', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (68, N'0054', N'Line Level Return Code 23: Denied Revenue Codes', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (69, N'0130', N'Per Service Automatic Rate Enhancement Add-on – Florida Medicaid', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (70, N'0131', N'Hospital Level Policy Adjustments', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (71, N'0132', N'Line Level Policy Adjustments', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (72, N'0055', N'Line Level Return Code 32: Invalid Billed Units', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (73, N'0056', N'Line Level Return Code 29: Non Covered APGs', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (74, N'0058', N'Potentially Preventable Readmission (PPR) Extended Factor - Adjustment to Base and Outlier Add-On Payment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (75, N'0007', N'Return Code 24: Non-covered claim', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (76, N'0059', N'Capital Adjustment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (77, N'0060', N'DRG Per Diem 1 Reimbursement', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (78, N'0061', N'DRG Per Diem 2 Reimbursement', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (79, N'0205', N'Transfer Per Diem Payment Capped at Base (LOS)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (80, N'0307', N'Calculate High Cost Threshold With Wage Index and Adjustment(includes base)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (81, N'0308', N'Calculate Cost With Adjustment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (82, N'0133', N'Fee Schedule Pricing without Charge Cap with discount', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (83, N'0057', N'Line Level Return Code 20: Consolidation with JW Modifier', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (84, N'0058', N'Line Level Return Code 33: Invalid or Missing Required Claims Data', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (85, N'0134', N'Fee Schedule Payments with Discount for Units Greater Than Maximum', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (86, N'0135', N'Use Fee Schedule Rate 2 for Specific Revenue Codes', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (87, N'0008', N'Return Code 16: Invalid Billing of Alternate Level of Care Days', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (88, N'0062', N'DRG Per Diem 3 Reimbursement', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (89, N'0063', N'DRG Per Diem 1 Reimbursement with DX Requirements', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (90, N'0064', N'Set Length of Stay (Indiana Medicaid)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (91, N'0065', N'Per Diem Capital Addon', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (92, N'0066', N'Per Diem Medical Education Addon', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (93, N'0067', N'Inter-governmental Fund Calculation', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (94, N'0068', N'Policy Adjustment 3', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (95, N'0069', N'Inlier Only Policy Adjustment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (96, N'0309', N'Calculate Multiple Outlier Thresholds (Indiana Medicaid)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (97, N'0310', N'High Cost Outlier with Two Marginal Cost Factors based on DRG Category', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (98, N'0503', N'Non-covered Day Payment Reduction', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (99, N'0504', N'Distributed Charge Cap', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (100, N'1001', N'Adjust Base and Capital Rate by Provider Adjustor', 1, 84)
GO
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (101, N'1002', N'Non-covered Days Adjustment Factor', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (102, N'1003', N'Find Principal Diagnosis', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (103, N'0070', N'DRG Per Diem 1 with Weights', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (104, N'0071', N'DRG Per Diem 2 with Weights', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (105, N'0072', N'Capital Add-On', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (106, N'0073', N'Same Day Discharge Reduction', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (107, N'0074', N'Provider Adjustment Factor', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (108, N'0206', N'Transfer Capped at Charges', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (109, N'0311', N'DRG specific Cost Outlier Threshold', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (110, N'0312', N'True Cost with ALC Charges', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (111, N'0313', N'ALC Payments', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (112, N'0314', N'Cost Outlier Threshold with Two Fixed Cost Outlier Amounts', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (113, N'1004', N'Calculate Per Diem Factor', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (114, N'1005', N'ALC Charges', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (115, N'0009', N'Return Code 18: Invalid Occurrence Span Date', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (116, N'0010', N'Return Code 08: Day Outlier Claim Zero-Divide Error', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (117, N'0136', N'Distributed Charge Cap', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (118, N'0137', N'Inpatient LARC', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (119, N'0315', N'Day Outlier (LOS, Variable Per Diem)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (120, N'1006', N'Set Covered Length of Stay', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (121, N'0316', N'Cost Outlier Threshold with Two Fixed Cost Outlier Amounts and Medical Education Addon', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (122, N'0075', N'Post Acute Care Per Diem with Revenue Code Requirement', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (123, N'0004', N'Claim Level Return Code 48: Reason for Visit Not Found', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (124, N'0005', N'Claim Level Return Code 52 and 47: Invalid Billing of APL codes - Illinois Medicaid', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (125, N'0138', N'Find Principal Diagnosis', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (126, N'0139', N'Find APL Code/Revenue Pair - Illinois Medicaid', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (127, N'0140', N'Calculate Cost - Line Level', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (128, N'0141', N'Calculate Threshold - Line Level', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (129, N'0142', N'High Cost Outlier - Line Level', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (130, N'0143', N'Distributed Charge Cap', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (132, N'0011', N'Return Code 08: Partial Eligibility Claim Zero Divide Error', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (133, N'0076', N'Reserved', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (134, N'0077', N'DRG Policy Adjustment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (135, N'0078', N'Policy Adjustment 4', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (136, N'0079', N'Newborn Policy Add-on', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (137, N'0317', N'Flat High Cost Threshold', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (138, N'0318', N'High Cost Using Gross Gain and Day Outlier Add-on Payment (Rhode Island Medicaid)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (139, N'0505', N'Partial Eligibility Adjustment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (140, N'0144', N'Determine Max Units for Discounting', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (141, N'0145', N'Fee Schedule Payments with Charge Cap and no Packaging and Consolidation', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (142, N'0146', N'Fee Schedule Payments without Charge Cap, Packaging and Consolidation', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (143, N'0147', N'Line Level VNS Add-on - Florida Medicaid', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (144, N'0148', N'ER Payment Reduction - Virginia Medicaid', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (145, N'0080', N'VNS Payments', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (146, N'1007', N'Find Multiple Policy Add-on Procedure', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (147, N'0012', N'Return Code 13: Same Day Discharge Denial', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (148, N'0081', N'Policy Adjustment 5', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (149, N'0082', N'Hospital Per Diem 1 Reimbursement with Weight', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (150, N'0207', N'Interim Claim Payment with Day and Cost Threshold', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (151, N'0319', N'Low Side Outlier (Paid Per Diem)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (152, N'0149', N'Fee Schedule Payments with Charge Cap and no Packaging and Consolidation - Ohio Medicaid', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (153, N'0150', N'Age Based Policy Adjustments', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (154, N'0013', N'Determine if Birthweight is Required - Admission Age in Days', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (155, N'0083', N'Policy Adjustment 6', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (156, N'0084', N'Base Payment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (157, N'0085', N'Inlier Policy Adjustment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (158, N'0086', N'Outlier Policy Adjustment', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (159, N'0087', N'Policy Adjustment 7', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (160, N'0506', N'Per Diem Addon 1', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (161, N'0507', N'Per Diem Add-on with DRG Restriction 1', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (162, N'0508', N'Per Diem Add-on with DRG Restriction 2', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (163, N'0509', N'Fee Rate Addon (LARC - Illinois Medicaid)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (164, N'1008', N'Adjusted Base Rate', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (166, N'0088', N'Medical Education Add-on Adjusted by Weight', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (167, N'0089', N'Organ Transplant Adjustment (Ohio Medicaid)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (168, N'0208', N'Interim Claim Paid Costs', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (169, N'0320', N'Calculate Costs excluding Organ Acquisition Charges (Ohio Medicaid)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (170, N'0321', N'Hospital or DRG Specific Outlier Threshold (includes base)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (171, N'1009', N'Organ Charges and Costs (Ohio Medicaid)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (172, N'0014', N'Return Code 46: Birth Weight in Grams Outside Allowed Range', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (173, N'0209', N'Exclude Transfers from Outlier', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (174, N'0322', N'Calculate High Cost Threshold using Outlier Factor', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (175, N'0151', N'Diagnosis Code Table Lookup', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (176, N'0152', N'Pay Minimum Allowed Amount', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (177, N'0153', N'Per Service Children’s Hospital Add-on - Florida Medicaid', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (178, N'0090', N'Newborn Policy Add-on 2', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (179, N'0510', N'DRG Policy Add-on 2', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (180, N'0511', N'Capped at Cost', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (181, N'1010', N'Bypass Charge Cap for Certain DRGs on Same Day Claims', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (182, N'0001', N'Return Code 25: Non-Payment Claim', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (183, N'0002', N'Return Code 21: Invalid POA Coding', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (184, N'0003', N'Return Code 27: Never Event', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (185, N'0004', N'Return Code 08: Transfer Claim Zero-Divide Error', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (186, N'0005', N'Return Code 73 & 07: Lookup DRG Weight and Stats with Return Code 07/73', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (187, N'0006', N'Return Code 86: Code Table Not Found', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (188, N'0007', N'Return Code 97: Error Reading Grouper Files', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (189, N'0051', N'Claim Level Code Table Lookup', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (190, N'0055', N'Group Medicaid Specific DRGs', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (191, N'0056', N'Collect Claim Mask Attributes (OK)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (192, N'0057', N'Base Rate', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (193, N'0058', N'Calculate Transfer LOS as (LOS +1)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (194, N'0059', N'Pay Transfer 1', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (195, N'0060', N'Set Transfer Base as Inlier/DRG MLOS', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (196, N'0061', N'Set Transfer as Inlier/DRG MLOS', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (197, N'0062', N'Calculate True Costs', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (198, N'0063', N'Calculate Cost Outlier Threshold', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (199, N'0064', N'Set Marginal Cost Factor', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (200, N'0065', N'Calculate Cost Outlier Addon Payment', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (201, N'0066', N'Set Outlier Output', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (202, N'0067', N'Charge Cap', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (203, N'0068', N'Markup', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (204, N'NEED', N'Always be included', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (205, N'0091', N'Hospital Per Diem 1 Reimbursement', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (206, N'0154', N'Daily Hospital Addon - Illinois Medicaid', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (207, N'0512', N'Fee Rate Addon', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (208, N'1011', N'Find Fee Rate Addon (Genome Sequencing - Florida Medicaid)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (209, N'0092', N'Policy Adjustment 8', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (210, N'0006', N'Claim Level Return Code 27: Wrong Procedure Performed', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (211, N'0155', N'Cap Fee Schedule at Max Units', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (212, N'0156', N'Pay Discounted Charges', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (213, N'0157', N'Set Pricing Method for Fee Schedule Capped at Max Units', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (214, N'0158', N'Procedure Code/Modifier Pair Add-On Payment', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (215, N'0159', N'Distributed Charge Cap, APG Lines Only', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (216, N'0160', N'Set Method for Fee Schedule Lines without a Rate', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (217, N'0513', N'Provider Adjustment Factor (1 + Adjustor)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (218, N'1012', N'Adjust Base Rate and Capital Rate by Provider Adjustor 2', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (219, N'0161', N'Distribution of Payment', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (220, N'0008', N'Return Code 16: Invalid Billing of ALC Days', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (221, N'0054', N'HCPCs Level Code Table Lookup', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (222, N'0069', N'Bill Type Per Diem 1 Reimbursement', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (223, N'0070', N'Group Medicaid Specific DRGs (IA)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (224, N'0071', N'Calculate Transfer LOS as (LOS)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (225, N'0072', N'Calculate Cost Outlier Threshold 2 (flat base * weight * factor)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (226, N'0073', N'Set Cost Outlier Threshold (max of Threshold1 or Threshold2)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (227, N'0074', N'Calculate Day Outlier LOS as (LOS - Non-Covered Days)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (228, N'0075', N'Calculate Long Stay Outlier Addon Payment', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (229, N'0076', N'Set Long Stay Per Diem as Inlier/DRG MLOS', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (230, N'0077', N'Set Covered Days 1', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (231, N'0078', N'Set Short Stay Per Diem as Inlier/DRG MLOS', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (232, N'0079', N'Calculate Short Stay Outlier Addon Payment', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (233, N'0080', N'Additional Payment', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (234, N'0081', N'Apply Short Stay Payment', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (235, N'0082', N'Determine Non-covered Days', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (236, N'0083', N'Set Long Stay Marginal Cost Factors', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (237, N'0162', N'Determine Multiple Discounting Rules', 1, 86)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (238, N'0009', N'Return Code 13: Same Day Discharge', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (239, N'0053', N'Procedure Level Code Table Lookup', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (240, N'0084', N'Set Short Stay Marginal Cost Factor', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (241, N'0085', N'Set transfer flag (NC)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (242, N'0086', N'Group Medicaid-Specific DRGs (NC)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (243, N'0087', N'DRG Per Diem 1', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (244, N'0088', N'DRG Per Diem 2', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (245, N'0089', N'Combined Direct and Indirect Medical Education', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (246, N'0090', N'Apply Medical Education to Base', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (247, N'0091', N'Long Stay Outlier Eligibility', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (248, N'0092', N'Long Stay Outlier Eligibility (Children) (NC)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (249, N'0093', N'Set Covered Days 2', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (250, N'0094', N'Calculate Cost Outlier Threshold 2 (flat rate)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (251, N'0095', N'Calculate Cost Outlier Threshold (DRG Rate)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (252, N'0098', N'Set Outlier Output 2 (NC)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (253, N'0099', N'Apply Claim Factor 2 (1 + Factor 2)', 1, 96)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (254, N'0323', N'Day Outlier (Covered Days, Flat Per Diem)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (255, N'0324', N'Set Day Outlier Threshold', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (256, N'1013', N'Set Covered Days', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (257, N'0015', N'Return Code 24: Non-Covered Claim Due to Zero Covered Days', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (258, N'0093', N'Provider Adjustment Factor with Age Requirement, Outlier Only (1 + Adjustor)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (259, N'0094', N'Provider Adjustment Factor with Age Requirement, Inlier Only (1 + Adjustor)', 1, 84)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (260, N'001', N'Claim Level Return Code 44: No Zip Code Provided', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (261, N'002', N'Claim Level Return Code 44: Service Zip Code Required for Patient Home', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (262, N'003', N'Claim Level Return Code 44: No Carrier Associated with Zip Code', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (263, N'004', N'Claim Level Return Code 43: Place of Service Not Applicable for Medicare', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (264, N'005', N'Claim Level Return Code 42: No Place of Service on Line', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (265, N'006', N'Claim Level Return Code 42: More than one Place of Service on Claim', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (266, N'007', N'Claim Level Return Code 42: Invalid Place of Service', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (267, N'050', N'Line Level Return Code 37: Missing or Invalid Status Code', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (268, N'051', N'Line Level Return Code 10: Line Item Denial or Rejection from Editor', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (269, N'052', N'Line Level Return Code 43: Editor Flagged as Not Enough Information for Pricing', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (270, N'053', N'Line Level Return Code 34: Service not Payable', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (271, N'054', N'Line Level Return Code 35: Service for Reporting Purposes Only', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (272, N'055', N'Line Level Return Code 45: Cannot Derive MPFS Payment Percentage', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (273, N'056', N'Line Level Return Code 16: Claim Contains a Never Event', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (274, N'057', N'Line Level Return Code 11: Invalid Units for Modifier', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (275, N'058', N'Line Level Return Code 32: Pricing Cannot be Provided for NDC', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (276, N'059', N'Line Level Return Code 33: Conditionally Bundled Service not Separately Payable', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (277, N'060', N'Line Level Return Code 33: Always Bundled Service not Separately Payable', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (278, N'061', N'Line Level Return Code 08: Invalid Bilateral Modifiers Provided for Pricing', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (279, N'062', N'Line Level Return Code 40: Anesthesia Time Units Divide by Zero Error', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (280, N'063', N'Line Level Return Code 42: Invalid or Missing Place of Service', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (281, N'064', N'Line Level Return Code 43: Not Enough Information for Pricing Provided', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (282, N'065', N'Line Level Return Code 36: Carrier Priced', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (283, N'066', N'Line Level Return Code 13: Zip Code Missing or Invalid', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (284, N'067', N'Line Level Return Code 08: Modifier Rejected for Pricing', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (285, N'068', N'Line Level Return Code 10: Line Item Denial or Rejection from Editor except MUE', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (286, N'100', N'Determine Payment Zip Code', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (287, N'101', N'Determine Status Code', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (288, N'102', N'Determine Payment Type for Status Code E or Payment Code 1', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (289, N'103', N'Determine if Anesthesia Service', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (290, N'104', N'Set Adjusted Rate to TC Rate + PC Rate', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (291, N'105', N'Charge Cap', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (292, N'106', N'Specialty Discount Lookup Using Taxonomy', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (293, N'107', N'HCPCS Code Lookup', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (294, N'108', N'NDC Lookup', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (295, N'109', N'Determine Fractional Units', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (296, N'110', N'Determine Non-Ambulance Carriers by Zip Code', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (297, N'111', N'Determine Ambulance Carrier by Zip Code', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (298, N'112', N'Fee Schedule Lookup', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (299, N'113', N'Identify Lines for NDC Payment if HCPCS Rate is Unavailable', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (300, N'114', N'Apply Coverage and Coinsurance to Total Payment', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (301, N'115', N'NDC Payment (NDC Rate * NDC Units)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (302, N'116', N'Determine OTA Reduction Eligibility', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (303, N'117', N'Determine PTA Reduction Eligibility', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (304, N'118', N'Set Non-MPFS Payment Type (Medicare)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (305, N'119', N'Set MPFS Payment Type (Medicare)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (306, N'120', N'Remove Fee Schedule Lookup Return Codes to Continue Processing', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (307, N'121', N'Determine Anesthesia Time Units with Modifier AD', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (308, N'122', N'Determine Coverage and Coinsurance Factors, and Carrier for All Fee Types', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (309, N'123', N'Determine Anesthesia Base Units with Modifier AD', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (310, N'124', N'Pay Reasonable Charges', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (311, N'125', N'Charge Cap for Endoscopy Services', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (312, N'126', N'Non-MPFS Fee Schedule Total Payment (Rate * Units)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (313, N'127', N'Waive Coinsurance', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (314, N'128', N'Determine Coverage and Coinsurance Factors for Anesthesia Services', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (315, N'129', N'Conditionally Set Anesthesia Time Units to Zero', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (316, N'130', N'Set Anesthesia Base Units from Fee Schedule', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (317, N'131', N'Zip Code Lookup', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (318, N'132', N'Set Anesthesia Conversion Factor from Fee Schedule', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (319, N'133', N'Anesthesia Total Payment ((Base Units + Time Units) * Conversion Factor)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (320, N'134', N'Apply Anesthesia Reduction for Modifier QK', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (321, N'135', N'Apply Anesthesia Reduction for Modifier QX', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (322, N'136', N'Apply Anesthesia Reduction for Modifier QY', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (323, N'137', N'Determine Ambulance Fee Schedule Rate (Medicare)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (324, N'138', N'Fee Schedule Total Payment (Rate)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (325, N'139', N'Fee Schedule Total Payment for Ground Mileage (Medicare)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (326, N'140', N'Apply Ambulance Multiple Patient Mileage Adjustment', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (327, N'141', N'Apply Ambulance Multiple Patient Transport Adjustment', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (328, N'142', N'Determine DME Fee Schedule Rate', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (329, N'143', N'Determine Lab Fee Schedule Rate', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (330, N'144', N'Determine National or Medicaid Fee Schedule Rate', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (331, N'145', N'Determine Physician Fee Schedule Rate', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (332, N'146', N'Determine User Defined Fee Schedule Rate', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (333, N'147', N'Set Markup/Discount Factors', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (334, N'148', N'Determine Non-Facility MPFS Rate', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (335, N'149', N'Determine Facility MPFS Rate', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (336, N'150', N'Determine TC/PC Rate for MPPR 4, 6 and 7', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (337, N'151', N'Determine TC/PC Rate for Modifiers "FX", "FY" and "CT"', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (338, N'152', N'Determine Number of Ambulance Patients and Corresponding Reduction Factor', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (339, N'153', N'Determine Rate for Endoscopy Base Code', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (340, N'154', N'MPPR 3 - Pre-Processing for Multiple Endoscopic Service Discounting', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (341, N'155', N'Determine Conditionally Bilateral Services Billed with RT and LT', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (342, N'156', N'Bundle Conditionally Bilateral LT Line into RT Line and Apply Adjustment', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (343, N'157', N'Apply Conditionally Bilateral Adjustment (Modifier 50)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (344, N'158', N'Apply Independently Bilateral Adjustment (Modifier 50)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (345, N'159', N'MPPR 3 - Discounting for Multiple Endoscopic Procedures', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (346, N'160', N'MPPR 4 - Discounting for Multiple Diagnostic Imaging Procedures', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (347, N'161', N'MPPR 6 - Discounting for Multiple Cardiovascular Procedures', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (348, N'162', N'MPPR 7 - Discounting for Multiple Ophthalmology Procedures', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (349, N'163', N'MPPR 5 - Discounting for Multiple Therapy Services', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (350, N'164', N'MPPR 2 and 3 - Discounting for Multiple Procedures', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (351, N'165', N'Set Coverage and Coinsurance Factors for MPFS Paid Lines', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (352, N'166', N'MPFS Fee Schedule Total Payment (Rate * Units)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (353, N'167', N'Apply FX Reduction', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (354, N'168', N'Apply FY Reduction', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (355, N'169', N'Apply CT Reduction', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (356, N'170', N'Determine Co-Surgery Adjustment (Medicare Indicator & Modifier 62)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (357, N'171', N'Apply Co-Surgery Adjustment', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (358, N'172', N'Determine Assistant at Surgery Adjustment (Medicare Indicator & Modifier AS)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (359, N'173', N'Determine Assistant at Surgery Adjustment (Medicare Indicator & Modifier 80)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (360, N'174', N'Determine Assistant at Surgery Adjustment (Medicare Indicator & Modifier 81)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (361, N'175', N'Determine Assistant at Surgery Adjustment (Medicare Indicator & Modifier 82)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (362, N'176', N'Apply Assistant at Surgery Adjustment', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (363, N'177', N'Apply Pre-Op, Intra-Op, and Post-Op Adjustments to Global Surgery (Medicare)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (364, N'178', N'Determine Specialty Discount Eligibility (Medicare)', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (365, N'179', N'Apply Specialty Discount', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (366, N'180', N'Specialty Code Lookup', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (367, N'181', N'Modifier Lookup', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (368, N'182', N'Apply OTA/PTA Reduction', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (369, N'183', N'Apply Markup/Discount', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (370, N'184', N'Determine if Coinsurance Applies', 1, 98)
INSERT [dbo].[LUT_PricerTypeAPRPro_Procedure] ([LUTPID], [PCode], [PDescription], [Enabled], [LUTPTID]) VALUES (371, N'NEED', N'Always be included', 1, 98)
